### ISSUE TITLE
 data set

### ISSUE THREAD

**Issue by 2151330** [Rulzz/Author-Identification#1]
Hello, would you please share the data set, thank you very much

**Comment by Rulzz** [comment]
Datasets: 
1. C50 dataset Reuters 50 authors, 50 articles each.
2. Gutenberg Dataset 50 authors, 900 paragraphs each

Following are the two datasets links:
https://archive.ics.uci.edu/ml/datasets/Reuter_50_50
https://web.eecs.umich.edu/~lahiri/gutenberg_dataset.html

**Comment by 2151330** [comment]
Thanks again, you are very friendly.

**Comment by 2151330** [comment]
I'm sorry to bother you again, can you share your 'glove.6B.50d.txt' file easily?

**Comment by Rulzz** [comment]
You can find the glove file online as well-
https://nlp.stanford.edu/projects/glove/
https://www.kaggle.com/watts2/glove6b50dtxt
